USE libronova;

CREATE TABLE book(
id INT PRIMARY KEY AUTO_INCREMENT,
isbn VARCHAR(50) NOT NULL UNIQUE,
tittle VARCHAR(100) NOT NULL,
author VARCHAR(50) NOT NULL,
stock INT NOT NULL,
available BOOLEAN NOT NULL DEFAULT TRUE,
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ,
update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE partner(
id INT PRIMARY KEY AUTO_INCREMENT,
code_partner VARCHAR(20) NOT NULL UNIQUE,
fullname VARCHAR(150) NOT NULL,
phonenumber VARCHAR(50) NOT NULL,
statu_partner BOOLEAN NOT NULL DEFAULT TRUE,
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan(
id INT PRIMARY KEY AUTO_INCREMENT,
code_partner VARCHAR(20),
isbn_book VARCHAR(50),
loan_date TIMESTAMP,
return_date TIMESTAMP,
statu_loan ENUM('ACTIVO','PENDIENTE','VENCIDO') NOT NULL,
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

FOREIGN KEY (code_partner) REFERENCES partner(code_partner),
FOREIGN KEY (isbn_book) REFERENCES book(isbn)
);

SELECT * FROM book;
SELECT * FROM partner;
SELECT * FROM loan;